# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'display_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1632, 1307)
        self.parent_widget = QtWidgets.QWidget(Form)
        self.parent_widget.setGeometry(QtCore.QRect(0, -14, 1251, 1031))
        self.parent_widget.setObjectName("parent_widget")
        self.z_vs_x_widget = QtWidgets.QWidget(self.parent_widget)
        self.z_vs_x_widget.setGeometry(QtCore.QRect(-10, 20, 711, 251))
        self.z_vs_x_widget.setObjectName("z_vs_x_widget")
        self.widget = QtWidgets.QWidget(self.parent_widget)
        self.widget.setGeometry(QtCore.QRect(20, 270, 681, 671))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 671))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.crosshair_widget = QtWidgets.QWidget(self.parent_widget)
        self.crosshair_widget.setGeometry(QtCore.QRect(700, 20, 331, 251))
        self.crosshair_widget.setObjectName("crosshair_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.crosshair_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.crosshairButton = QtWidgets.QPushButton(self.crosshair_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crosshairButton.sizePolicy().hasHeightForWidth())
        self.crosshairButton.setSizePolicy(sizePolicy)
        self.crosshairButton.setBaseSize(QtCore.QSize(1, 1))
        self.crosshairButton.setIconSize(QtCore.QSize(1, 1))
        self.crosshairButton.setObjectName("crosshairButton")
        self.gridLayout.addWidget(self.crosshairButton, 0, 1, 1, 1)
        self.crosshair_width = QtWidgets.QSpinBox(self.crosshair_widget)
        self.crosshair_width.setObjectName("crosshair_width")
        self.gridLayout.addWidget(self.crosshair_width, 4, 1, 1, 1)
        self.crosshair_x = QtWidgets.QDoubleSpinBox(self.crosshair_widget)
        self.crosshair_x.setObjectName("crosshair_x")
        self.gridLayout.addWidget(self.crosshair_x, 2, 1, 1, 1)
        self.crosshair_y = QtWidgets.QDoubleSpinBox(self.crosshair_widget)
        self.crosshair_y.setObjectName("crosshair_y")
        self.gridLayout.addWidget(self.crosshair_y, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.crosshair_widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.crosshair_widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.clear_crosshair_Button = QtWidgets.QPushButton(self.crosshair_widget)
        self.clear_crosshair_Button.setObjectName("clear_crosshair_Button")
        self.gridLayout.addWidget(self.clear_crosshair_Button, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.crosshair_widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.center_Button = QtWidgets.QPushButton(self.crosshair_widget)
        self.center_Button.setObjectName("center_Button")
        self.gridLayout.addWidget(self.center_Button, 6, 1, 1, 1)
        self.crosshair_step = QtWidgets.QLineEdit(self.crosshair_widget)
        self.crosshair_step.setObjectName("crosshair_step")
        self.gridLayout.addWidget(self.crosshair_step, 5, 1, 1, 1)
        self.z_vs_y_widget = QtWidgets.QWidget(self.parent_widget)
        self.z_vs_y_widget.setGeometry(QtCore.QRect(700, 270, 331, 611))
        self.z_vs_y_widget.setObjectName("z_vs_y_widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.crosshairButton.setText(_translate("Form", "Crosshair"))
        self.label_3.setText(_translate("Form", "y:"))
        self.label_4.setText(_translate("Form", "step"))
        self.clear_crosshair_Button.setText(_translate("Form", "Clear Crosshair"))
        self.label.setText(_translate("Form", "x:"))
        self.center_Button.setText(_translate("Form", "center"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
